Repository SinguloStation13/SinguloStation13, pull requests merged in 2022-12, with the labels that each got.

#323 [PORT] Fix failing tests
  .github/workflows/continuous_integration.yml
Labels: GitHub

#360 Fixes code broken by Bee's changes (and my own negligence)
  _maps/map_files/ConstructionStation/ConstructionStation.dmm
  config/game_options.txt
  singulostation/code/game/machinery/autodoc.dm
  singulostation/code/game/machinery/cryopod.dm
  tools/ci/check_grep.sh
  whitesands/code/modules/mining/deepcore/drill.dm
  whitesands/code/modules/mining/deepcore/hopper.dm
Labels: Config Update, mapping, tools

#350 Gives Stations Holofans So Cryo Rooms Don't Get Fucking Spaced
  _maps/map_files/ConstructionStation/ConstructionStation.dmm
  _maps/map_files/CryoStation/CryoStation.dmm
Labels: mapping

#325 Expands construction station a bit, adds a bridge!
  _maps/map_files/ConstructionStation/ConstructionStation.dmm
Labels: mapping

#376 lavaland fix
  _maps/map_files/Mining/Lavaland.dmm
Labels: mapping

#377 Two Construction Station fixes
  _maps/map_files/ConstructionStation/ConstructionStation.dmm
Labels: mapping
